workspace = { members = ["q_20240502_claude3_karano_mondai"] }
[package]
name = "rust-playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "1.3.1"
tokio = { version = "1.37.0", features = ["full"] }
