name: rust lint & format
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: cargo build
      - name: check
        run: cargo check
      # - name: clippy
      #   run: cargo clippy -- -D warnings
      - name: fmt
        run: cargo fmt -- --check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: cargo test
  # run:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: run
  #       run: cargo run
